name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        
        run: echo "logging into Docker"
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PW}}
        
        run: echo "building latest image"
        run: docker build -t "avmagnaye/batgenomedatabase:latest" .

        run: echo "pushing image to Docker Repositoy"
        run: docker image push "avmagnaye/batgenomedatabase:latest"
